const CONFIG = {
    titleWeb: "Website Title",
    introTitle: "Your Lover's Name",
    introDesc: `The world is such a strange place,
    Yet somehow you took the wrong way,
    And got lost in my lonely heart,
    Behind the word ‘love’ lies deep affection.`,
    btnIntro: '^^HiHi^^',
    title: 'Did you fall in love at first sight? 🥰',
    desc: 'Or was it my smile that made your heart flutter?',
    btnYes: 'Absolutely <33',
    btnNo: 'Nope :3',
    question: 'Out of more than 7 billion people in the world, why did you fall for me? <3',
    btnReply: 'Send to me <3',
    reply: 'Love is love — no choice, just love <33333333',
    mess: 'I knew it 🥰 Love you so so much 😘😘',
    messDesc: 'I’ll pick you up at 7 tonight, okay?',
    btnAccept: 'Okiiiii <3',
    messLink: 'https://github.com/zukahai/Confess-Crush' // your messenger link, e.g. https://www.facebook.com/messages/t/100014188333536
};
